Hidden labels
geological-survey-of-queensland/vocabularies pull request #329
Opened 2020-10-22 03:09 UTC by KellyVance

Addition of hidden labels, addition of alternative labels, and derivation of additional UOMs (magnitude additions to existing types) to align vocabularies with Petroleum data submission templates.

2020-10-22 05:57 UTC, johnmckellar approved these changes
All look good to me.

2020-10-22 21:37 UTC, DavidCrosswellGSQ requested changes
A couple of changes required to geounits

2020-10-22 21:37 UTC, DavidCrosswellGSQ commented on vocabularies/geounits.ttl
> +    skos:altLabel "Million BBLs Oil Equiv. (MMBOE)"@en,
```suggestion
    skos:altLabel "Million BBLs Oil Equiv. (MMBOE)"@en ;
```

2020-10-22 21:37 UTC, DavidCrosswellGSQ commented on vocabularies/geounits.ttl
> +        "Million Tonnes"@en
```suggestion
        "Million Tonnes"@en  ;
```

2020-10-22 22:24 UTC, johnmckellar commented on vocabularies/geounits.ttl
> +    skos:altLabel "Million BBLs Oil Equiv. (MMBOE)"@en,
OK

2020-10-22 22:55 UTC, johnmckellar commented on vocabularies/geounits.ttl
> +        "Million Tonnes"@en
OK too

2020-10-22 23:52 UTC, johnmckellar commented on vocabularies/geounits.ttl
> +        "Million Tonnes"@en
Sorry, missed this & OK

2020-10-25 22:21 UTC, KellyVance commented
geounits syntax errors fixed.

2020-10-25 22:40 UTC, DavidCrosswellGSQ approved these changes

2020-10-25 22:40 UTC, merged