Update dq-iso-19157.ttl
geological-survey-of-queensland/vocabularies pull request #364
Opened 2021-01-27 21:56 UTC by UbuntuScott

Vocprez is showing an "invalid vocab id' for the Dimensions of Data Quality vocab.  
Found a spelling error in the rdfs and skos labels. 

Wondering if this is the cause of the issue.

2021-01-28 00:53 UTC, broughd-qld requested changes
@UbuntuScott - Just updated the labels for the vocab to be consistent with other vocabs that use ISO. If we are going to tweak a name, maybe go all out.

2021-01-28 00:53 UTC, broughd-qld commented on vocabularies/dq-iso-19157.ttl
> +  rdfs:label "Dimensions of data quality (ISO 19157)"@en ;
```suggestion
  rdfs:label "ISO19157 Data Quality Dimensions"@en ;
```

2021-01-28 00:53 UTC, broughd-qld commented on vocabularies/dq-iso-19157.ttl
> +  skos:prefLabel "Dimensions of data quality (ISO 19157)"@en ;
```suggestion
  skos:prefLabel "ISO19157 Data Quality Dimensions"@en ;
```

2021-02-09 04:26 UTC, broughd-qld approved these changes
Looks good to go!

2021-02-09 04:27 UTC, UbuntuScott commented
General tidy up 
+ removal of RDFS labels,
+addition of Metaquality terms, 
correction to publisher -from GSQ to DES

2021-02-23 00:18 UTC, KellyVance approved these changes

2021-02-23 21:59 UTC, merged