Update dq-nsw-data-quality-assessment.ttl
geological-survey-of-queensland/vocabularies pull request #365
Opened 2021-02-07 08:54 UTC by UbuntuScott

Nick Car review 
DQ (this one) 
Dataset Relationships
Licence

2021-02-07 22:40 UTC, broughd-qld requested changes
Looks good, just a name change suggestion.

2021-02-07 22:40 UTC, broughd-qld commented on vocabularies/dq-nsw-data-quality-assessment.ttl
>    skos:prefLabel "Dimensions of data quality"@en ;
```suggestion
  skos:prefLabel "NSW Government Data Quality Dimensions"@en ;
```

2021-02-07 22:40 UTC, broughd-qld commented on vocabularies/dq-nsw-data-quality-assessment.ttl
>    skos:prefLabel "Dimensions of data quality"@en ;
Just a slightly better name if removing the label.

2021-03-02 21:48 UTC, broughd-qld approved these changes

2021-03-02 23:25 UTC, johnmckellar approved these changes

2021-03-03 01:47 UTC, KellyVance approved these changes

2021-03-03 02:48 UTC, merged