Johnmckellar patch 1
geological-survey-of-queensland/vocabularies pull request #424
Opened 2022-02-24 05:26 UTC by johnmckellar

This vocab was withdrawn as it was deemed stale for want of review.

A new review is requested in terms of the status of a geologic feature. Please compare with GA's ASUD and consider what is required in terms of our needs for RU-data transfer from MERLIN.

Micaela, I have thus added you to the review list.

Cheers,

John

2022-08-08 06:05 UTC, KellyVance requested changes
Generally need to upscale this to make it more general and widely applicable.
Fairly straight forward changes

2022-08-08 22:47 UTC, johnmckellar commented on vocabularies/gsq-feature-status.ttl
> +    skos:prefLabel "Unnamed rock unit"@en .
Vance (& Paul), just another note on DEF (now formal): Not all RUs meet the definition provided by Paul (which was derived from MERLIN?) in that some are informal. This largely encompasses RUs defined as 'beds', which are not recognized as formal units. These will need to be weeded out.

2022-08-09 01:05 UTC, johnmckellar commented
I take it that I need to close this!!??

2022-08-09 02:04 UTC, KellyVance commented on vocabularies/gsq-feature-status.ttl
> +    skos:prefLabel "Unnamed rock unit"@en .
@johnmckellar 
If you agree with the unnamed edit, can you please commit that, and if not update as needed?
As part of the attribute mapping we can include the IF status = DEF and strat = beds -> Informal

Once those commits are done i'll merge and close the pull request. Then i'll be able to update our vocprez

2022-08-09 03:42 UTC, KellyVance approved these changes

2022-08-09 03:42 UTC, merged